from typing import Protocol
from app.domain.models.alert import VehicleAlert
from app.domain.enums import AlertType
from app.domain.value_objects.vehicle_id import VehicleId

class AlertRepository(Protocol):
    def save(self, alert: VehicleAlert) -> None: ...
    def get_active(self, vehicle_id: VehicleId) -> list[VehicleAlert]: ...
    def clear(self, vehicle_id: VehicleId, alert_type: AlertType) -> bool: ...
    def upsert(self, alert: VehicleAlert) -> None: ...
