from typing import Protocol
from app.domain.models.diagnostic_code import DiagnosticCode
from app.domain.value_objects.vehicle_id import VehicleId

class DiagnosticRepository(Protocol):
    def save(self, code: DiagnosticCode) -> None: ...
    def get_active(self, vehicle_id: VehicleId) -> list[DiagnosticCode]: ...
    def get_by_code(self, vehicle_id: VehicleId, code: str) -> DiagnosticCode | None: ...
    def clear(self, vehicle_id: VehicleId, code: str) -> bool: ...
