from typing import Protocol
from app.domain.models.telemetry import TelemetrySnapshot
from app.domain.value_objects.vehicle_id import VehicleId

class TelemetryRepository(Protocol):
    def save(self, snapshot: TelemetrySnapshot) -> None: ...
    def get_latest(self, vehicle_id: VehicleId) -> TelemetrySnapshot | None: ...
    def get_history(self, vehicle_id: VehicleId) -> list[TelemetrySnapshot]: ...
