from typing import Protocol
from app.domain.models.trip import TripSession
from app.domain.value_objects.vehicle_id import VehicleId
from app.domain.value_objects.trip_id import TripId

class TripRepository(Protocol):
    def save(self, trip: TripSession) -> None: ...
    def get_active(self, vehicle_id: VehicleId) -> TripSession | None: ...
    def get(self, trip_id: TripId) -> TripSession | None: ...
    def get_latest_completed(self, vehicle_id: VehicleId) -> TripSession | None: ...
